### ISSUE TITLE
FromBytes and ToBytes

### ISSUE THREAD

**Issue by rylev** [rust-secure-code/mem-markers#1]
There is very handy pair of traits for expressing that types have well defined layouts in memory. These are (note that names are subject to change):
* `AsBytes` - It is completely sound to view a type `T: AsBytes` as bytes. There is no part of the type's layout in memory that is not well defined. Things that can cause this to not be true include (but are not limited to) not having a stable layout (e.g., not `#[repr(C)]`) or having padding. 
* `FromBytes` - it is completely sound to view a properly aligned and sized slice of bytes as a given type `T: FromBytes`. While such types can have non-well defined parts (e.g., padding), they cannot have any parts that are not "byte complete" (i.e., any part where any bit pattern is a valid representation). 

## Examples 

Examples of types that would implement one of the traits but not another are:
* `bool` implements `AsBytes` but not `FromBytes` since any `bool` can be viewed as a byte but not all bytes are valid `bool`s (i.e., only `0` and `1` are valid `bool`s)
* `struct Foo(u8, u16)` is `FromBytes` but not `AsBytes` since it contains padding - meaning we can construct this type from any sufficiently aligned and sized slice of bytes but we cannot view this type as bytes in a sound way since the padding bytes values are undefined. 

## Prior Art  
* `zerocopy` defines `AsBytes` and `FromBytes` which mirror the definitions above
* `bytemuck` includes only a `Pod` trait which is valid for any types that are `AsBytes + FromBytes`.
* `safe_transmute` defines `TriviallyTransmutable` which is just like `bytemuck`'s `Pod` trait.
* `typic` does not have equivalents to these traits instead relying on even more base primitives for describing a given type's layout in memory and comparing that to `generic_array::Array<u8, typic::SizeOf<T>>`. Typic also has `Transparent` which similarly to `FromBytes` ensures that there are no additional validity restrictions to the type beyond padding, alignment, and size.

**Comment by jswrenn** [comment]
@rylev [asked](https://rust-lang.zulipchat.com/#narrow/stream/216762-project-safe-transmute/topic/Marker.20Traits/near/191230330):
> I'd also love to hear from you two since it's the least clear how well this plays into a typic style solution.

It's somewhere between helpful and hostile, with "inapplicable" sitting somewhere in between those two extremes. The two variables that will determine where these traits fall are:
1. Are they applied automatically?
2. Will `#![feature(marker_trait_attr)]` be stabilized?

#### \*–Yes: _Helpful_
If `marker_trait_attr` is stabilized, then the presence or absence of these traits can be one more avenue by which typic's underlying `FromType<U>` marker trait can be implemented for a `T` and `U`.

#### Yes–No: _Inapplicable_
If these traits are applied automatically, then typic's own `FromBytes` and `AsBytes` blanket implementations are somewhat redundant. (Typic's `FromBytes` and `AsBytes` trait are just convenient aliases of `TransmuteFrom<u8 as Array<SizeOf<U>>` and `TransmuteInto<u8 as Array<SizeOf<Self>>`.)

#### No–No: _Hostile_
If these traits are not applied automatically and `marker_trait_attr` is not stabilized, the presence of these traits is slightly hostile to the existence of typic's blanket implementation of its own traits, since they'll probably differ slightly in semantics.

**Comment by jswrenn** [comment]
> Typic also has Transparent which similarly to FromBytes ensures that there are no additional validity restrictions to the type beyond padding, alignment, and size.

FWIW, with jswrenn/typic#5, the `Transparent` trait is being eliminated. All non-ZST and non-`pub` fields of a type `T` are now simply assumed to have validity invariants placed on them by `T`. Typic also has [a marker-trait grammar for expressing size, validity and alignment guarantees](https://github.com/jswrenn/typic/blob/631a71a76620338bb98483d9eb207a24f6de0c14/typic/src/private/stability.rs).

By default, Typic statically forbids transmutes that are unstable, unsafe, or unsound, but lets you [_explicitly_ opt-out](https://hackmd.io/@jswrenn/HydSGVHS8#Transmute-Options) of these guarantees.

**Comment by rylev** [comment]
> Are they applied automatically?

These traits probably should not be applied automatically as they make guarantees about the stability of a type that the author may not want. Even if all the fields of the type are public, the author may not want to commit to that type always being `ToBytes`. So I believe these types should always be opt in.

> Will `#![feature(marker_trait_attr)]` be stabilized?

This is something I can't answer, though if the ultimate goal is to move these traits to the std lib, then in the long run that doesn't really matter. Perhaps you think this is necessary though even when experimenting with these traits outside the std lib?

Bringing in @Lokathor's comments:
> **Lokathor**: I think that ToBytes and FromBytes are perhaps too broad and could be broken up into sub-markers and then you have ToBytes any time you have NoUninit and also FixedLayout
> 
> **Lokathor**: But they should exist somewhere, so feel free to go ahead.

So it seems that while perhaps these traits are useful,  they can be expressed in terms of other traits. Do we want to then create traits for `NoUninit` and `FixedLayout`?

**Comment by RustyYato** [comment]
> Even if all the fields of the type are public, the author may not want to commit to that type always being `ToBytes`.

Given that it would be a breaking change to add, remove or change the fields of a type with all public fields, the only way to change the type so that `ToBytes` doesn't apply requires a breaking change. So it should be fine to auto implement `ToByes`/`FromBytes` when all fields are public, and all fields implemented `ToByes`/`FromBytes`.

But even so, I think that `ToBytes` should be opt in. Unless we integrate `ToBytes` into the compiler, Rust has no way of correctly and automatically implementing this trait. 

> Do we want to then create traits for `NoUninit` and `FixedLayout`?

I think this would be a good idea. Especially if we move this into std. We can then automatically implement `FixedLayout` if any of the repr attributes are applied, and make `NoUninit` an opt-in trait.

**Comment by rylev** [comment]
Both `FromBytes` and `ToBytes` are now in master along with derives for them and the traits that they comprise `FromBytes: FixedLayout + ByteComplete` and `AsBytes: FixedLayout + NoUninit`. The derives for these traits are not completely feature complete but I think we will open issues for the missing features instead of keeping this open.
