### ISSUE TITLE
Usefulness of ByteComplete 

### ISSUE THREAD

**Issue by rylev** [rust-secure-code/mem-markers#14]
Right now we have the distinction between a `ByteComplete` type (a type where all byte patterns are legal representations of this type) and a `FromBytes` type (a type that can be instantiated from any appropriately sized and aligned array of bytes) where `FromBytes` is simply `ByteComplete + FixedLayout`. 

How useful is this distinction between `ByteComplete` and `FromBytes`? When is it useful to know that a type is byte complete but it's not necessarily a fixed layout?

One possible distinction that might be useful (that we're not currently enforcing) is that `FromBytes` types must be completely public accessible because in a sense it offers a way to instantiate these types from bytes. `ByteComplete` on the other hand only says that a type is always valid no matter what byte pattern it's in but it does not allow the user to arbitrarily instantiate it in whatever form they desire so the fields do not need to be public (just `ByteComplete` themselves). 

While this makes some sense, I'm having trouble coming up with an example where a type that is `ByteComplete` but not `FromBytes` is useful to know.

**Comment by scottmcm** [comment]
As potentially another phrasing of your third paragraph, maybe the difference between validity and safety invariants can help you here.

Because something like ByteComplete could be an auto trait for the _validity_ invariant -- something that's true structurally -- whereas `FromBytes` is something that you opt into to say that it's also _safe_ to make this thing from any byte pattern, and is thus what actually enables the safe methods.

For example, if something is `ByteComplete` than I can `calloc` a bunch of them without needing to wrap everything in pointers or `MaybeUninit`.

**Comment by Lokathor** [comment]
Yeah, safety is key.

Probably Copy needs to be in there somewhere as well.

**Comment by rylev** [comment]
I like the point about calloc. I think `ByteComplete` is a more general version of the `Zeroable` trait.
